Trying to log more info about the failure, but not sure if this will work with set -e

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -30,7 +30,12 @@ for BUILDPACK in $(cat $1/.buildpacks); do
       mkdir -p "$dir"
       curl -s "$url" | tar xvz -C "$dir" >/dev/null 2>&1
     else
-      git clone $url $dir >/dev/null 2>&1
+      output=$(git clone $url $dir >/dev/null 2>&1)
+      if [[ "$?" != "0" ]]; then
+        echo "There was an error downloading the code"
+        echo $output
+        exit $?
+      fi
     fi
     cd $dir
 
